name: {{project_name.snakeCase()}}_api
description: A {{app_name}} server app built with the dart_frog package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  collection: ^1.19.0
  dart_frog: ^1.2.6
  equatable: ^2.0.7
  http: ^1.6.0
  json_annotation: ^4.9.0
  news_blocks:
    path: packages/news_blocks

dev_dependencies:
  build_runner: ^2.10.4
  json_serializable: ^6.11.3
  mocktail: ^1.0.4
  test: ^1.28.0
  very_good_analysis: ^10.0.0

dependency_overrides:
  frontend_server_client: ^4.0.0