name: {{storage_name.snakeCase()}}_storage
description: Storage abstraction for {{storage_name.lowerCase()}} data
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  storage:
    path: ../storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  test: ^1.21.4
  very_good_analysis: ^10.0.0
